extern __errno_location
extern accept
extern access
extern bind
extern close
extern closedir
extern dprintf
extern exit
extern free
extern getcwd
extern htons
extern listen
extern malloc
extern memset
extern open
extern opendir
extern perror
extern read
extern readdir
extern recv
extern send
extern setsockopt
extern socket
extern sprintf
extern stat
extern strlen
extern strncat
extern strncpy
extern strtok_r
extern strtol